"""Pinned Gen 9 rolls generated by the independent @smogon/calc oracle.

The fixture records the oracle version and every input. Mew's base stats and
types were overridden to isolate rounding; ability defaults were Pressure.
"""

import json
from pathlib import Path

import pytest

from vgc_mcp_core.calc.damage import (
    calculate_bulk_threshold,
    calculate_damage,
    calculate_ko_threshold,
)
from vgc_mcp_core.calc.modifiers import DamageModifiers
from vgc_mcp_core.models.move import Move
from vgc_mcp_core.models.pokemon import BaseStats, PokemonBuild

CASES = json.loads(Path(__file__).with_name("damage_audit_cases.json").read_text())["cases"]
CASES += json.loads(Path(__file__).with_name("damage_oracle_matrix.json").read_text())["cases"]
STAT_NAMES = {
    "hp": "hp", "atk": "attack", "def": "defense",
    "spa": "special_attack", "spd": "special_defense", "spe": "speed",
}


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
def test_exact_damage_matches_smogon(case):
    base = BaseStats(**{STAT_NAMES[key]: value for key, value in case["base"].items()})
    types = case.get("types", ["Normal"])
    attacker = PokemonBuild(name="Mew", base_stats=base, types=types, level=case["level"])
    defender = PokemonBuild(name="Mew", base_stats=base, types=types, level=case["level"])
    move = Move(**case["move"])
    result = calculate_damage(attacker, defender, move, DamageModifiers(**case["mods"]))
    assert result.rolls == case["rolls"]


@pytest.mark.parametrize("format_system", ["mainline", "champions"])
def test_multihit_optimizers_use_independent_probabilities(format_system):
    base = BaseStats(hp=100, attack=100, defense=100, special_attack=100,
                     special_defense=100, speed=100)
    attacker = PokemonBuild(name="Mew", base_stats=base, types=["Water"],
                            format_system=format_system)
    defender = PokemonBuild(name="Mew", base_stats=base.model_copy(update={"hp": 5}),
                            types=["Normal"], format_system=format_system)
    move = Move(name="surging-strikes", type="water", category="physical", power=25)
    result = calculate_damage(attacker, defender, move)
    # @smogon/calc 0.11.0 per-hit rolls:
    # [24]*5 + [25]*5 + [27]*5 + [28]. Exactly 396/4096 sums reach 80 HP.
    assert result.ohko_percent == 396 / 4096 * 100
    assert result.survival_percent == 3700 / 4096 * 100
    # The evenly-spaced display rolls misleadingly suggest 37.5% OHKO.
    assert sum(r >= result.defender_hp for r in result.rolls) / 16 == 0.375
    bulk = calculate_bulk_threshold(attacker, defender, move, target_survival_chance=90)
    assert bulk is not None
    assert bulk.get("hp_evs", bulk.get("hp_sps")) == 0
    assert bulk.get("def_evs", bulk.get("def_sps")) == 0
    offense = calculate_ko_threshold(attacker, defender, move, target_ko_chance=30)
    assert offense is not None
    assert offense.get("evs_needed", offense.get("sps_needed")) > 0
